### ISSUE TITLE
Dark mode only works on my Mac with dark mode enabled

### ISSUE THREAD

**Issue by larryathey** [Clashsoft/bootstrap-darkmode#22]
As the subject line says, this dark mode switch only seems to work on my Mac with dark mode enabled in my desktop theme settings. Viewing the same page on any other computer, the dark mode does not work. I can't even begin to explain how this is possible. I'm wondering if anybody else can.

![image](https://user-images.githubusercontent.com/20978773/101842974-785aef00-3b06-11eb-855f-a4300cd8011e.png)

**Comment by larryathey** [comment]
As a followup, when looking at the developer tools in Chrome on my Mac, it clearly says < body data-theme="dark" > but the same page when viewed on any other computer shows < body data-theme="light" >. How can this CSS be dependent upon a person's desktop settings? Better yet, how can I over-ride that?

**Comment by Clashsoft** [comment]
This is the behaviour of `themeConfig.init()`:

https://github.com/Clashsoft/bootstrap-darkmode/blob/d48cc10b8f7cbda113f85496241ba578c9d41162/theme.ts#L18

It tries to load the theme from localStorage, and if none is saved, it detects the theme using the `(prefers-color-scheme: dark)` media query. On your Mac, that query matches because you have system-wide dark mode, and on your other computers it does not match.

Now the fix depends on what you intend to do. Do you always want to use the system theme for your website? Then you can just use `<body data-theme="auto">` and get rid of the JavaScript altogether. `ThemeConfig` is not recommended for production use anyway, the logic is simple enough that you can replicate it to fit into your architecture and intended usage.

**Comment by larryathey** [comment]
OK, I got it forced on like I wanted it to. I needed to be able to use a variable in PHP to turn dark mode on/off and was not aware that this could be done by manually setting the < body data-theme="" > tag.
